asn3.out: main.c BankAccount.h
	gcc -v -pthread main.c -o asn3.out
debug: main.c BankAccount.h
	gcc -v -pthread -g main.c -o debug
# bank: BankAccount.c BankAccount.h
# 	gcc -v -pthread -g BankAccount.c -o bank
clean:
	rm -v asn3.out assignment_3_output_file.txt